---

# Play 1 Configuring R1 

- name: Configuring R1
  hosts: Cisco1
  gather_facts: false

  tasks:
    - name: Configuring Loopback address on R1
      ios_command:
        commands:
          - show ip in brief

# Play 2 Configuring R2


- name: Configuring R2
  hosts: Cisco2
  gather_facts: false

  tasks:
    - name: Configuring Loopback address on R2
      cisco.ios.ios_config:
        lines:
          - interface lo0
          - ip address 10.2.2.2 255.255.255.255

# Play 3 Configuring R3

- name: Configuring R3
  hosts: Cisco3
  gather_facts: false

  tasks:
    - name: Configuring Loopback address on R3
      cisco.ios.ios_config:
        lines:
          - interface lo0
          - ip address 10.3.3.3 255.255.255.255
